// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const assert = require('assert');

let opts = new chrome.Options();
let WaitAndClick = async(driver, method, locator) => {
  await driver.wait(until.elementLocated(By[method](locator)), 25000);
  await driver.findElement(By[method](locator)).click();
}

let WaitAndSelect = async(driver, method_select, locator_select, method_opt, locator_opt) => {
  let select_element = await driver.findElement(By[method_select](locator_select));
  await select_element.click();
  await driver.wait(until.elementIsEnabled(await select_element.findElement(By[method_opt](locator_opt))), 25000);
  await select_element.findElement(By[method_opt](locator_opt)).click();
}

describe('ERC20', function() {
  this.timeout(100000)
  let driver
  let vars
  before(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(opts.headless()).build()
    vars = {}
  })
  after(async function() {
    await driver.quit();
  })
  it('Lock Native token 1st time', async function() {
    // Test name: Lock Native token 1st time
    // Step # | name | target | value
    // 1 | open | http://localhost:3006/login | 
    await driver.get("http://localhost:3006/login")
    // 2 | runScript | window.localStorage.clear() | 
    await driver.executeScript("window.localStorage.clear()")
    // 3 | waitForElementEditable | id=lgUsername | 30000
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.id("lgUsername"))), 100000)
    // 4 | setWindowSize | 1070x824 | 
    await driver.manage().window().maximize()
    // 5 | click | id=lgUsername | 
    await driver.findElement(By.id("lgUsername")).click()
    // 6 | type | id=lgUsername | testtest
    await driver.findElement(By.id("lgUsername")).sendKeys("testtest")
    // 7 | click | id=lgPassword | 
    await driver.findElement(By.id("lgPassword")).click()
    // 8 | type | id=lgPassword | 1234567
    await driver.findElement(By.id("lgPassword")).sendKeys("1234567")
    
    await driver.wait(until.elementLocated(By.css(".submit_bar")), 100000)
    const submit_bar = await driver.findElement(By.css(".submit_bar"));
    await driver.executeScript("arguments[0].scrollIntoView()", submit_bar);
    await driver.wait(until.elementIsVisible(submit_bar), 100000);
    // 9 | click | css=.submit_bar | 
    await driver.executeScript("arguments[0].click()", submit_bar);

    await driver.wait(until.elementLocated(By.id("receiverAddress")), 100000)
    // 10 | click | css=.large_div:nth-child(3) > .large_input_transparent | 
    await driver.findElement(By.css(".large_div:nth-child(3) > .large_input_transparent")).click()
    // 11 | click | css=.large_div:nth-child(2) > .large_input_transparent | 
    await driver.findElement(By.css(".large_div:nth-child(2) > .large_input_transparent")).click()
    // 12 | click | id=amountEther | 
    await driver.findElement(By.id("amountEther")).click()
    // 13 | type | id=amountEther | 0.00001
    await driver.findElement(By.id("amountEther")).sendKeys("0.00001")
    // 14 | click | css=.col-lg-5:nth-child(1) .small_input_transparent | 
    await driver.wait(until.elementLocated(By.id("fromNetwork")), 100000);
    const fromNetwork = await driver.findElement(By.id("fromNetwork"));
    await driver.executeScript("arguments[0].scrollIntoView()", fromNetwork);
    await driver.wait(until.elementIsVisible(fromNetwork), 100000);

    await driver.executeScript("arguments[0].click()", fromNetwork);
    // 15 | click | css=.inputBox > .sep_bottom:nth-child(1) > p:nth-child(1) | 
    await driver.findElement(By.css(".inputBox > .sep_bottom:nth-child(1) > p:nth-child(1)")).click()
    // 16 | click | id=senderAddress | 

    await driver.wait(until.elementLocated(By.id("senderAddress")), 100000)
    const senderAddress = await driver.findElement(By.id("senderAddress"));
    await driver.executeScript("arguments[0].scrollIntoView()", senderAddress);
    await driver.wait(until.elementIsVisible(senderAddress), 100000);

    await driver.executeScript("arguments[0].click()", senderAddress);
    // 17 | type | id=senderAddress | 0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8
    await driver.findElement(By.id("senderAddress")).sendKeys("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8")
    // 18 | click | id=receiverAddress | 
    const receiverAddress = await driver.findElement(By.id("receiverAddress"));
    await driver.executeScript("arguments[0].click()", receiverAddress);
    // 19 | type | id=receiverAddress | 0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8
    await driver.findElement(By.id("receiverAddress")).sendKeys("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8")
    // 20 | click | css=.submit_bar | 
    const final_submit = await driver.findElement(By.css(".submit_bar"));
    await driver.executeScript("arguments[0].click()", final_submit);
    // 21 | assertText | id=btnStatus | Success!
    await driver.wait(until.elementLocated(By.id("btnStatus")), 100000);
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("btnStatus"))), 100000);
    assert(await driver.findElement(By.id("btnStatus")).getText() == "Success!")
    // 22 | assertElementPresent | css=.center:nth-child(8) > p | 
    {
      const elements = await driver.findElements(By.css(".center:nth-child(8) > p"))
      assert(elements.length)
    }
  })

  it('Unlock ERC20 1st time', async function() {
    // Test name: Unlock ERC20 1st time
    // Step # | name | target | value
    // 1 | open | http://localhost:3006/login | 
    await driver.get("http://localhost:3006/login")
    // 2 | runScript | window.localStorage.clear() | 
    await driver.executeScript("window.localStorage.clear()")
    // 3 | waitForElementEditable | id=lgUsername | 30000
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.id("lgUsername"))), 100000)
    // 4 | setWindowSize | 1070x824 | 
    await driver.manage().window().maximize()
    // 5 | click | id=lgUsername | 
    await driver.findElement(By.id("lgUsername")).click()
    // 6 | type | id=lgUsername | testtest
    await driver.findElement(By.id("lgUsername")).sendKeys("testtest")
    // 7 | click | id=lgPassword | 
    await driver.findElement(By.id("lgPassword")).click()
    // 8 | type | id=lgPassword | 1234567
    await driver.findElement(By.id("lgPassword")).sendKeys("1234567")
    
    await driver.wait(until.elementLocated(By.css(".submit_bar")), 100000)
    const submit_bar = await driver.findElement(By.css(".submit_bar"));
    await driver.executeScript("arguments[0].scrollIntoView()", submit_bar);
    await driver.wait(until.elementIsVisible(submit_bar), 100000);
    // 9 | click | css=.submit_bar | 
    await driver.executeScript("arguments[0].click()", submit_bar);
    
    
    // 10 | click | css=.large_div:nth-child(3) > .large_input_transparent | 
    await WaitAndClick(driver, "css", ".large_div:nth-child(3) > .large_input_transparent");
    // 11 | select | css=.large_div:nth-child(3) > .large_input_transparent | label=VMBC
    {
      const dropdown = await driver.findElement(By.css(".large_div:nth-child(3) > .large_input_transparent"));
      await driver.wait(until.elementIsEnabled(await dropdown.findElement(By.xpath("//option[@value = 'VMBC']"))), 10000);
      await dropdown.findElement(By.xpath("//option[@value = 'VMBC']")).click();
    }
    // 12 | click | css=.large_div:nth-child(2) > .large_input_transparent | 
    await driver.findElement(By.css(".large_div:nth-child(2) > .large_input_transparent")).click()
    // 13 | select | css=.large_div:nth-child(2) > .large_input_transparent | label=Draw
    {
      const dropdown = await driver.findElement(By.css(".large_div:nth-child(2) > .large_input_transparent"))
      await driver.wait(until.elementIsEnabled(await dropdown.findElement(By.xpath("//option[@value = 'Draw']"))), 10000);
      await dropdown.findElement(By.xpath("//option[@value = 'Draw']")).click()
    }


    // 14 | click | id=amountEther | 
    await driver.findElement(By.id("amountEther")).click()
    // 15 | type | id=amountEther | 0.00001
    await driver.findElement(By.id("amountEther")).sendKeys("0.00001")
    // 14 | click | css=.col-lg-5:nth-child(1) .small_input_transparent | 
    await driver.wait(until.elementLocated(By.id("fromNetwork")), 100000);
    const fromNetwork = await driver.findElement(By.id("fromNetwork"));
    await driver.executeScript("arguments[0].scrollIntoView()", fromNetwork);
    await driver.wait(until.elementIsVisible(fromNetwork), 100000);

    await driver.executeScript("arguments[0].click()", fromNetwork);
    // 15 | click | css=.inputBox > .sep_bottom:nth-child(1) > p:nth-child(1) | 
    await driver.findElement(By.css(".inputBox > .sep_bottom:nth-child(1) > p:nth-child(1)")).click()
    // 16 | click | id=senderAddress | 

    await driver.wait(until.elementLocated(By.id("senderAddress")), 100000)
    const senderAddress = await driver.findElement(By.id("senderAddress"));
    await driver.executeScript("arguments[0].scrollIntoView()", senderAddress);
    await driver.wait(until.elementIsVisible(senderAddress), 100000);

    await driver.executeScript("arguments[0].click()", senderAddress);
    // 17 | type | id=senderAddress | 0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8
    await driver.findElement(By.id("senderAddress")).sendKeys("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8")
    // 18 | click | id=receiverAddress | 
    const receiverAddress = await driver.findElement(By.id("receiverAddress"));
    await driver.executeScript("arguments[0].click()", receiverAddress);
    // 19 | type | id=receiverAddress | 0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8
    await driver.findElement(By.id("receiverAddress")).sendKeys("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8")
    // 20 | click | css=.submit_bar | 
    const final_submit = await driver.findElement(By.css(".submit_bar"));
    await driver.executeScript("arguments[0].click()", final_submit);
    // 21 | assertText | id=btnStatus | Success!
    await driver.wait(until.elementLocated(By.id("btnStatus")), 100000);
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("btnStatus"))), 100000)
    assert(await driver.findElement(By.id("btnStatus")).getText() == "Success!")
    // 22 | assertElementPresent | css=.center:nth-child(8) > p | 
    {
      const elements = await driver.findElements(By.css(".center:nth-child(8) > p"))
      assert(elements.length)
    }
  })

  it('Lock ERC20 1st time', async function() {
    // Test name: Lock ERC20 1st time
    // Step # | name | target | value
    // 1 | open | http://localhost:3006/login | 
    await driver.get("http://localhost:3006/login")
    // 2 | runScript | window.localStorage.clear() | 
    await driver.executeScript("window.localStorage.clear()")
    // 3 | waitForElementEditable | id=lgUsername | 30000
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.id("lgUsername"))), 100000)
    // 4 | setWindowSize | 1070x824 | 
    await driver.manage().window().maximize()
    // 5 | click | id=lgUsername | 
    await driver.findElement(By.id("lgUsername")).click()
    // 6 | type | id=lgUsername | testtest
    await driver.findElement(By.id("lgUsername")).sendKeys("testtest")
    // 7 | click | id=lgPassword | 
    await driver.findElement(By.id("lgPassword")).click()
    // 8 | type | id=lgPassword | 1234567
    await driver.findElement(By.id("lgPassword")).sendKeys("1234567")
    
    await driver.wait(until.elementLocated(By.css(".submit_bar")), 100000)
    const submit_bar = await driver.findElement(By.css(".submit_bar"));
    await driver.executeScript("arguments[0].scrollIntoView()", submit_bar);
    await driver.wait(until.elementIsVisible(submit_bar), 100000);
    // 9 | click | css=.submit_bar | 
    await driver.executeScript("arguments[0].click()", submit_bar);

    await driver.wait(until.elementLocated(By.id("receiverAddress")), 100000)
    // 10 | click | css=.large_div:nth-child(3) > .large_input_transparent | 
    await WaitAndSelect(driver, "css", ".large_div:nth-child(3) > .large_input_transparent", "xpath", "//option[@value = 'VMBC']");
    // 11 | click | css=.large_div:nth-child(2) > .large_input_transparent | 
    await driver.findElement(By.css(".large_div:nth-child(2) > .large_input_transparent")).click()
    // 12 | click | id=amountEther | 
    await driver.findElement(By.id("amountEther")).click()
    // 13 | type | id=amountEther | 0.00001
    await driver.findElement(By.id("amountEther")).sendKeys("0.00001")
    // 14 | click | css=.col-lg-5:nth-child(1) .small_input_transparent | 
    await driver.wait(until.elementLocated(By.id("fromNetwork")), 100000);
    const fromNetwork = await driver.findElement(By.id("fromNetwork"));
    await driver.executeScript("arguments[0].scrollIntoView()", fromNetwork);
    await driver.wait(until.elementIsVisible(fromNetwork), 100000);

    await driver.executeScript("arguments[0].click()", fromNetwork);
    await driver.wait(until.elementIsEnabled(await fromNetwork.findElement(By.xpath("//option[@value = 'AGD']"))), 10000);
    await fromNetwork.findElement(By.xpath("//option[@value = 'AGD']")).click();
    // 15 | click | css=.inputBox > .sep_bottom:nth-child(1) > p:nth-child(1) | 
    await driver.findElement(By.css(".inputBox > .sep_bottom:nth-child(1) > p:nth-child(1)")).click()
    // 16 | click | id=senderAddress | 

    await driver.wait(until.elementLocated(By.id("senderAddress")), 100000)
    const senderAddress = await driver.findElement(By.id("senderAddress"));
    await driver.executeScript("arguments[0].scrollIntoView()", senderAddress);
    await driver.wait(until.elementIsVisible(senderAddress), 100000);

    await driver.executeScript("arguments[0].click()", senderAddress);
    // 17 | type | id=senderAddress | 0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8
    await senderAddress.sendKeys("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8")
    // 18 | click | id=receiverAddress | 
    const receiverAddress = await driver.findElement(By.id("receiverAddress"));
    await driver.executeScript("arguments[0].click()", receiverAddress);
    // 19 | type | id=receiverAddress | 0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8
    await receiverAddress.sendKeys("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8")
    // 20 | click | css=.submit_bar | 
    const final_submit = await driver.findElement(By.css(".submit_bar"));
    await driver.executeScript("arguments[0].click()", final_submit);
    // 21 | assertText | id=btnStatus | Success!
    await driver.wait(until.elementLocated(By.id("btnStatus")), 100000);
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("btnStatus"))), 100000)
    assert(await driver.findElement(By.id("btnStatus")).getText() == "Success!")
    // 22 | assertElementPresent | css=.center:nth-child(8) > p | 
    {
      const elements = await driver.findElements(By.css(".center:nth-child(8) > p"))
      assert(elements.length)
    }
  })
  
  it('Unlock Native token 1st time', async function() {
    // Test name: Unlock Native token 1st time
    // Step # | name | target | value
    // 1 | open | http://localhost:3006/login | 
    await driver.get("http://localhost:3006/login")
    // 2 | runScript | window.localStorage.clear() | 
    await driver.executeScript("window.localStorage.clear()")
    // 3 | waitForElementEditable | id=lgUsername | 30000
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.id("lgUsername"))), 100000)
    // 4 | setWindowSize | 1070x824 | 
    await driver.manage().window().maximize()
    // 5 | click | id=lgUsername | 
    await driver.findElement(By.id("lgUsername")).click()
    // 6 | type | id=lgUsername | testtest
    await driver.findElement(By.id("lgUsername")).sendKeys("testtest")
    // 7 | click | id=lgPassword | 
    await driver.findElement(By.id("lgPassword")).click()
    // 8 | type | id=lgPassword | 1234567
    await driver.findElement(By.id("lgPassword")).sendKeys("1234567")
    
    await driver.wait(until.elementLocated(By.css(".submit_bar")), 100000)
    const submit_bar = await driver.findElement(By.css(".submit_bar"));
    await driver.executeScript("arguments[0].scrollIntoView()", submit_bar);
    await driver.wait(until.elementIsVisible(submit_bar), 100000);
    // 9 | click | css=.submit_bar | 
    await driver.executeScript("arguments[0].click()", submit_bar);
    
    
    // 10 | click | css=.large_div:nth-child(3) > .large_input_transparent | 
    await WaitAndClick(driver, "css", ".large_div:nth-child(3) > .large_input_transparent");
    // 12 | click | css=.large_div:nth-child(2) > .large_input_transparent | 
    await driver.findElement(By.css(".large_div:nth-child(2) > .large_input_transparent")).click()
    // 13 | select | css=.large_div:nth-child(2) > .large_input_transparent | label=Draw
    {
      const dropdown = await driver.findElement(By.css(".large_div:nth-child(2) > .large_input_transparent"))
      await driver.wait(until.elementIsEnabled(await dropdown.findElement(By.xpath("//option[@value = 'Draw']"))), 10000);
      await dropdown.findElement(By.xpath("//option[@value = 'Draw']")).click()
    }


    // 14 | click | id=amountEther | 
    await driver.findElement(By.id("amountEther")).click()
    // 15 | type | id=amountEther | 0.00001
    await driver.findElement(By.id("amountEther")).sendKeys("0.00001")
    // 14 | click | css=.col-lg-5:nth-child(1) .small_input_transparent | 
    await driver.wait(until.elementLocated(By.id("fromNetwork")), 100000);
    const fromNetwork = await driver.findElement(By.id("fromNetwork"));
    await driver.executeScript("arguments[0].scrollIntoView()", fromNetwork);
    await driver.wait(until.elementIsVisible(fromNetwork), 100000);

    await driver.executeScript("arguments[0].click()", fromNetwork);
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.xpath("//option[@value = 'AGD']"))), 25000);
    await driver.findElement(By.xpath("//option[@value = 'AGD']")).click();

    
    // 16 | click | id=senderAddress | 

    await driver.wait(until.elementLocated(By.id("senderAddress")), 100000)
    const senderAddress = await driver.findElement(By.id("senderAddress"));
    await driver.executeScript("arguments[0].scrollIntoView()", senderAddress);
    await driver.wait(until.elementIsVisible(senderAddress), 100000);

    await driver.executeScript("arguments[0].click()", senderAddress);
    // 17 | type | id=senderAddress | 0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8
    await driver.findElement(By.id("senderAddress")).sendKeys("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8")
    // 18 | click | id=receiverAddress | 
    const receiverAddress = await driver.findElement(By.id("receiverAddress"));
    await driver.executeScript("arguments[0].click()", receiverAddress);
    // 19 | type | id=receiverAddress | 0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8
    await driver.findElement(By.id("receiverAddress")).sendKeys("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8")
    // 20 | click | css=.submit_bar | 
    const final_submit = await driver.findElement(By.css(".submit_bar"));
    await driver.executeScript("arguments[0].click()", final_submit);
    // 21 | assertText | id=btnStatus | Success!
    await driver.wait(until.elementLocated(By.id("btnStatus")), 100000);
    await driver.wait(until.elementIsVisible(await driver.findElement(By.id("btnStatus"))), 100000);
    assert(await driver.findElement(By.id("btnStatus")).getText() == "Success!")
    // 22 | assertElementPresent | css=.center:nth-child(8) > p | 
    {
      const elements = await driver.findElements(By.css(".center:nth-child(8) > p"))
      assert(elements.length)
    }
  })
})
