// Generated by Selenium IDE
const { Builder} = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const {LockToken, LockNative, UnlockToken, UnlockNative} = require('./common');

let opts = new chrome.Options();

const {Login} = require("../utils/index");

describe('ERC20', function() {
  this.timeout(100000)
  let driver
  let vars
  before(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(opts.headless()).build()
    vars = {}
  })
  after(async function() {
    await driver.quit();
  })
  it('Lock Native token 1st time', async function() {
    await LockNative("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8", driver, null, Login);
  })

  it('Unlock ERC20 1st time', async function() {
    await UnlockToken("ERC20", "0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8", driver, null, Login, null, null, null, "AGD");
  })

  it('Lock ERC20 1st time', async function() {
    await LockToken("ERC20", "0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8", driver, null, Login, null, null, null, "AGD");
  })
  
  it('Unlock Native token 1st time', async function() {
    await UnlockNative("0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8", driver, null, Login);
  })
})
