// Generated by Selenium IDE
const { Builder} = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const {LockToken, UnlockToken} = require('./common');

let opts = new chrome.Options();

const {Login} = require("../utils/index");

describe('ERC721', function() {
  this.timeout(100000)
  let driver
  let vars
  before(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(opts.headless()).build()
    vars = {}
  })
  after(async function() {
    await driver.quit();
  })
  //token, address, driver, handle, Login, ConfirmMetamask, ConnectMetamask, SwitchNetwork, network, id
  it('Lock ERC721 token 1st time', async function() {
    await LockToken("ERC721", "0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8", driver, null, Login, null, null, null, "MBC", "70");
  })

  it('Unlock ERC721 1st time', async function() {
    await UnlockToken("ERC721", "0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8", driver, null, Login, null, null, null, "AGD", "70");
  })

  it('Lock ERC721 1st time from other side', async function() {
    await LockToken("ERC721", "0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8", driver, null, Login, null, null, null, "AGD", "70");
  })
  
  it('Unlock ERC721 token 1st time from other side', async function() {
    await UnlockToken("ERC721", "0xC3DDDE3D73927C503632ff13f9C6D8B20D67c2d8", driver, null, Login, null, null, null, "MBC",  "70");
  })
})
