// // Generated by Selenium IDE
// const { Builder, By, Key, until } = require('selenium-webdriver')
// const assert = require('assert')

// describe('Hello Search', function() {
//   this.timeout(100000)
//   let driver
//   let vars
//   beforeEach(async function() {
//     driver = await new Builder().forBrowser('chrome').build()
//     vars = {}
//   })
//   afterEach(async function() {
//     await driver.quit();
//   })
//   it('Hello Search', async function() {
//     // Test name: Hello Search
//     // Step # | name | target | value
//     // 1 | open | https://www.google.com/ | 
//     await driver.get("https://www.google.com/")
//     // 2 | setWindowSize | 1068x824 | 
//     await driver.manage().window().setRect({ width: 1068, height: 824 })
//     // 3 | click | css=.LLD4me | 
//     await driver.findElement(By.css(".LLD4me")).click()
//     // 4 | click | css=.LLD4me | 
//     await driver.findElement(By.css(".LLD4me")).click()
//     // 5 | click | css=.LLD4me | 
//     await driver.findElement(By.css(".LLD4me")).click()
//     // 6 | click | name=q | 
//     await driver.findElement(By.name("q")).click()
//     // 7 | type | name=q | hello
//     await driver.findElement(By.name("q")).sendKeys("hello")
//     // 8 | assertText | css=.sbhl .wM6W7d > span | Hello
//     await driver.wait(until.elementLocated(By.css(".sbhl .wM6W7d > span")), 100000);
//     assert(await driver.findElement(By.css(".sbhl .wM6W7d > span")).getText() == "Hello")
//     // 9 | click | css=.sbhl .wM6W7d > span | 
//     await driver.findElement(By.css(".sbhl .wM6W7d > span")).click()
//     // 10 | runScript | window.scrollTo(0,200) | 
//     await driver.executeScript("window.scrollTo(0,200)")
//     // 11 | click | css=html | 
//     await driver.findElement(By.css("html")).click()
//     // 12 | click | css=.TzHB6b:nth-child(5) .a-no-hover-decoration > .WeviRb > svg | 
//     await driver.wait(until.elementLocated(By.css(".TzHB6b:nth-child(5) .a-no-hover-decoration > .WeviRb > svg")), 100000);
//     await driver.findElement(By.css(".TzHB6b:nth-child(5) .a-no-hover-decoration > .WeviRb > svg")).click()
//     // 13 | runScript | window.scrollTo(0,0) | 
//     await driver.executeScript("window.scrollTo(0,0)")
//     // 14 | click | css=div:nth-child(2) > .LMRCfc .sATSHe | 
//     await driver.findElement(By.css("div:nth-child(2) > .LMRCfc .sATSHe")).click()
//     // 15 | click | id=rcnt | 
//     await driver.findElement(By.id("rcnt")).click()
//     // 16 | assertTitle | hello - Tìm trên Google | 
//     assert(await driver.getTitle() == "hello - Tìm trên Google")
//     // 17 | click | css=.WvKfwe > .g:nth-child(1) .LC20lb | 
//     await driver.findElement(By.css(".WvKfwe > .g:nth-child(1) .LC20lb")).click()
//     // 18 | assertTitle | Lời dịch bài hát Hello | VOCA.VN | 
//     assert(await driver.getTitle() == "Lời dịch bài hát Hello | VOCA.VN")}
//   )
// })
